server:
  port: 10002
spring:
  application:
    name: feifei-rabbitmq-consumer
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: feifei
    password: feifei
    virtual-host: feifei_vhosts